name: Docker Image CI

on:
  push:
    branches: [ "CU-*" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "CU-*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # - name: Install Jq tool
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install jq
    - name: Extract Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.DOCKER_USERNAME }}/python-docker
        tags: |
          # type=ref,event=branch
          # type=ref,event=pr
          type=ref,event=tags
          type=semver,pattern={{version}}
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        provenance: true
        sbom: true


    #   name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ vars.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build the Docker image and tag
    #   run: |
    #     tag=$(date +%s)
    #     ./bash/findtag.sh -n alokhom/python-docker -i 9ecb7a4b0adf -f 1.40.13 -l 10 -v
    #     # docker build . --file Dockerfile --tag python-docker:"${tag}" && docker tag python-docker:"${tag}" alokhom/python-docker:1.40.13

